backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: Posts
    folder: posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: slug, label: Slug, widget: string }
      - { name: date, label: Date, widget: date, format: YYYY-MM-DD }
      - { name: description, label: Description, widget: text }
      - { name: tags, label: Tags, widget: list }
      - { name: thumbnail, label: Featured Image,  widget: image }
      - { name: body, label: Body, widget: markdown }